import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { LogOut, Plus, ShieldCheck } from "lucide-react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/admin")({ head: () => ({ meta: [{ title: "Administration — Hiba Hamdi" }, { name: "description", content: "Espace privé de gestion des projets du portfolio de Hiba Hamdi." }, { name: "robots", content: "noindex, nofollow" }, { property: "og:title", content: "Administration — Hiba Hamdi" }, { property: "og:description", content: "Espace privé de gestion du portfolio." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Admin });

function Admin(){
 const [session,setSession]=useState<Session|null>(null); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 async function login(e:FormEvent){e.preventDefault();setMessage("");const {error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?"Accès refusé. Vérifiez vos identifiants.":"")}
 async function addProject(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const {error}=await supabase.from("projects").insert({title:String(fd.get("title")),category:String(fd.get("category")) as "Multimédia"|"IA",description:String(fd.get("description")),image_url:String(fd.get("image"))||null,github_url:String(fd.get("github"))||null,tools:String(fd.get("tools")).split(",").map(x=>x.trim()).filter(Boolean)});setMessage(error?`Erreur : ${error.message}`:"Projet ajouté au jardin !");if(!error)e.currentTarget.reset()}
 if(loading)return <main className="grid min-h-screen place-items-center bg-background text-primary">Ouverture du jardin privé...</main>;
 if(!session)return <main className="neural-grid grid min-h-screen place-items-center bg-background px-5"><form onSubmit={login} className="w-full max-w-md border border-primary/25 bg-paper p-8 shadow-[12px_12px_0_var(--forest-soft)]"><ShieldCheck className="size-10 text-accent"/><h1 className="mt-5 text-4xl text-primary">Jardin privé</h1><p className="mt-2 text-sm text-muted-foreground">Connectez-vous pour gérer les projets.</p><label className="mt-7 block text-sm" htmlFor="email">E-mail</label><Input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required className="mt-2 bg-background"/><label className="mt-5 block text-sm" htmlFor="password">Mot de passe</label><Input id="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required className="mt-2 bg-background"/><Button type="submit" variant="garden" className="mt-7 w-full">Entrer</Button>{message&&<p className="mt-4 text-sm text-destructive">{message}</p>}</form></main>;
 return <main className="min-h-screen bg-background px-5 py-12"><div className="mx-auto max-w-3xl"><header className="mb-10 flex items-start justify-between"><div><p className="text-sm font-semibold uppercase text-accent">Administration</p><h1 className="text-5xl text-primary">Ajouter un projet</h1></div><Button variant="ghost" size="icon" onClick={()=>supabase.auth.signOut()} aria-label="Se déconnecter"><LogOut/></Button></header><form onSubmit={addProject} className="grid gap-5 border border-primary/20 bg-paper p-7 sm:grid-cols-2 sm:p-10"><Field label="Titre" name="title" required/><label className="text-sm font-medium">Catégorie<select name="category" className="mt-2 h-10 w-full border border-input bg-background px-3"><option>Multimédia</option><option>IA</option></select></label><label className="text-sm font-medium sm:col-span-2">Description<Textarea name="description" required minLength={10} rows={5} className="mt-2 bg-background"/></label><Field label="Image (URL)" name="image" type="url"/><Field label="Lien GitHub" name="github" type="url"/><label className="text-sm font-medium sm:col-span-2">Outils<Input name="tools" placeholder="React, Python, Figma" className="mt-2 bg-background"/></label><div className="sm:col-span-2"><Button type="submit" variant="garden" size="lg"><Plus/>Ajouter au portfolio</Button>{message&&<p className="mt-4 text-sm font-medium text-primary" role="status">{message}</p>}</div></form></div></main>
}
function Field({label,name,type="text",required=false}:{label:string;name:string;type?:string;required?:boolean}){return <label className="text-sm font-medium">{label}<Input name={name} type={type} required={required} className="mt-2 bg-background"/></label>}